shell: /bin/bash
commands:
  git-root:
    run: git rev-parse --show-toplevel
  go-files:
    run: find . -name "*.go" -exec ls -l \{\} \;
  broken:
    # A deliberately broken command
    run: foo bar wibble
  compound:
    needs:
      - git-root
      - go-files
    run: echo "Hello world!"
  ls:
    run: ls
  lazygit:
    if: "! command -v lazygit"
    command: brew install jesseduffield/lazygit/lazygit
