commands:
  - name: git-show
    command: git show
  - name: git-root
    command: git rev-parse --show-toplevel
  - name: go-files
    command: find . -name *.go -exec ls -l {} ;
  - name: broken
    command: foo bar wibble
