shell: /bin/bash
commands:
  - name: git-show
    command: git show
  - name: git-root
    command: git rev-parse --show-toplevel
  - name: go-files
    command: find . -name "*.go" -exec ls -l \{\} \;
  - name: broken
    command: foo bar wibble
  - name: multiline
    command: |
      ls -la
      ls
  - name: compound
    command: |
      if [[ -e foo ]]; then
        echo foo
      else
        echo bar
      fi
