shell: /bin/bash
commands:
  git-root:
    command: git rev-parse --show-toplevel
  go-files:
    command: find . -name "*.go" -exec ls -l \{\} \;
  broken:
    # A deliberately broken command
    command: foo bar wibble
  readme-stats:
    command: |
      if [[ -e README.md ]]; then
        wc README.md
      else
        echo "Couldn't find README.md"
      fi
  compound:
    pre:
      - git-root
      - go-files
    command: echo "Hello world!"
    post:
      - git-root
