shell: /bin/bash
commands:
  git-root:
    run: git rev-parse --show-toplevel
  go-files:
    run: find . -name "*.go" -exec ls -l \{\} \;
  broken:
    # A deliberately broken command
    run: foo bar wibble
  readme-stats:
    if: "! test -e README.stats"
    run: wc README.md > README.stats
  compound:
    needs:
      - git-root
      - go-files
    run: echo "Hello world!"
