shell: /bin/bash
commands:
  git-show:
    command: git show
  git-root:
    command: git rev-parse --show-toplevel
  go-files:
    command: find . -name "*.go" -exec ls -l \{\} \;
  broken:
    command: foo bar wibble
  multiline:
    command: |
      ls -la
      ls
  compound:
    pre:
      - git-root
      - go-files
    command: echo "Hello world!"
    post:
      - git-root
