shell: /bin/zsh
env:
  - FOO=fooster
  - BAR=barbara
commands:
  # Commands I use when developing runny
  clean:
    run: |
      go clean ./...
      rm -rf dist
  install-goreleaser:
    if: "! command -v goreleaser"
    run: brew install goreleaser/tap/goreleaser
  install-pre-commit:
    if: "! command -v pre-commit"
    run: brew install pre-commit
  release:
    argnames:
      - tag
    run: git tag -am $tag $tag && git push origin refs/tags/$tag
  generate:
    run: go generate ./...
  test:
    run: go test ./...

  # Demo commands to showcase various features of runny
  demo-env:
    env:
      - FOO=baz
    run: echo $FOO $BAR
  demo-args:
    argnames:
      - aa
      - bb
    run: echo $aa is not $bb and $bb is not $aa
  demo-multiline-command:
    # Unlike Makefiles, runny makes it simple to run commands that span over multiple lines. Just write them exactly as
    # you would in a regular script.
    run: |
      for x in 1 2 3; do
        echo $x
      done
  demo-broken:
    run: foo bar

  demo-broken-dependency:
    needs:
      - demo-broken
    run: ls
