shell: /bin/bash
commands:
  clean:
    run: |
      go clean ./...
      rm -rf dist
  install-prek:
    internal: true
    if: "! command -v prek"
    run: brew install prek
  install-pre-commit-hooks:
    needs:
      - install-prek
    run: prek install --overwrite
  install-fish-completions:
    # Homebrew installs these for you, but this is useful if you're installing with `go install .`
    run: ln -s $PWD/completions/runny.fish ~/.config/fish/completions
  release:
    argnames:
      - tag
    run: git tag -am $tag $tag && git push origin refs/tags/$tag
  release-next:
    run: |
      latest_version=$(git tag --list "v*" --sort "-refname" | head -1)
      next_version=$(echo ${latest_version} | awk -F. -v OFS=. '{$NF += 1 ; print}')
      printf "Release $next_version? (Current release is $latest_version) [yN] "
      read answer
      if [[ $answer =~ ^[Yy]$ ]]; then
        git tag -am $next_version $next_version && git push origin refs/tags/$next_version
      fi
  generate:
    run: go generate ./...
  test:
    run: go test ./...
  test-coverage:
    run: go test -coverprofile=c.out ./... && go tool cover -func="c.out"
  test-coverage-html:
    run: go test -coverprofile=c.out ./... && go tool cover -html="c.out"
  update-deps:
    run: go get -u . && go mod tidy
