shell: /bin/bash
env:
  - FOO=fooster
  - BAR=barbara
commands:
  clean:
    run: |
      go clean ./...
      rm -rf dist
  install-goreleaser:
    if: "! command -v goreleaser"
    run: brew install goreleaser/tap/goreleaser
  install-pre-commit:
    if: "! command -v pre-commit"
    run: brew install pre-commit
  release:
    needs:
      - clean
      - install-goreleaser
    run: |
      export GITHUB_TOKEN=$(gh auth token)
      goreleaser
  generate:
    run: go generate ./...
  test:
    run: go test ./...
  test-env:
    env:
      - FOO=baz
    run: echo $FOO $BAR
