name: Deployment

on:
  push:
    # run only against version tags
    tags:
      - "v*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    # Generates the Github release, and updates the simonwhitaker/tap/gibo
    # Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Create GitHub App token
        uses: actions/create-github-app-token@v2
        id: github-app-token
        with:
          app-id: ${{ vars.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            runny
            homebrew-tap

      # More assembly might be required: Docker logins, GPG, etc. It all depends
      # on your needs.
      - uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ steps.github-app-token.outputs.token }}
